trigger: none

pool:
  name: 'Agent-Self-Hosted'

stages:
  - stage: initilization
    displayName: build Stage
    jobs:
    - job: initandplan
      displayName: init
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Storage_With_Module/Parent Module'''
          backendServiceArm: 'nt-spn'
          backendAzureRmStorageAccountName: 'ntstg19'
          backendAzureRmContainerName: 'nt-container'
          backendAzureRmKey: 'terraform.tfstate'