trigger:
  branches:
    include:
      - main

pool:
  name: 'Agent-Self-Hosted'  # Self-hosted agent pool name

variables:
  terraformWorkingDirectory: 'Storage_With_Module/Parent Module'  # Change if your Terraform files are in a subfolder

stages:
- stage: TerraformDeploy
  jobs:
  - job: TerraformJob
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'nt-spn'
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(terraformWorkingDirectory)
        inlineScript: |
          terraform init \
            -backend-config="storage_account_name=ntstg19" \
            -backend-config="container_name=nt-container" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="resource_group_name=nt-stg"

          terraform plan

          terraform apply -auto-approve
