trigger:
- main

pool:
  name: 'Agent-Self-Hosted'  # Self-hosted agent pool name

steps:
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)Storage_With_Module/Parent Module'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'nt-spn'
    backendAzureRmStorageAccountName: 'ntstg19'
    backendAzureRmContainerName: 'nt-container'
    backendAzureRmKey: 'terraform.tfstate'