trigger: none

variables:
  poolName: 'Agent-Self-Hosted'
  terraformVersion: 'latest'
  provider: 'azurerm'
  serviceConnection: 'nt-spn'
  storageAccountName: 'ntstg19'
  containerName: 'nt-container'
  stateFileKey: 'terraform.tfstate'
  mainWorkingDir: '$(System.DefaultWorkingDirectory)/Storage_With_Module/Parent Module'
  validateWorkingDir: '$(System.DefaultWorkingDirectory)/Storage_With_Module'

pool:
  name: $(poolName)

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(terraformVersion)
- task: TerraformTask@5
  displayName: INIT
  inputs:
    provider: $(provider)
    command: 'init'
    workingDirectory: $(mainWorkingDir)
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: $(serviceConnection)
    backendAzureRmStorageAccountName: $(StorageAccountName)
    backendAzureRmContainerName: $(containerName)
    backendAzureRmKey: $(stateFileKey)

- task: TerraformTask@5
  displayName: Validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: $(validateWorkingDir)
- task: TerraformTask@5
  displayName: Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: $(mainWorkingDir)
    environmentServiceNameAzureRM: 'nt-spn'